image: node:latest

before_script:
  - apt-get update && apt-get install -y build-essential libudev-dev libstdc++6 libusb-1.0-0-dev
  - npm install -g truffle
  - npm install
  - cp src/config.js.dist src/config.js

stages:
  - lint

run_js_linter:
  stage: lint
  script:
    - truffle compile
    - npm run lint

