image: node:10-alpine

before_script:
  - apk add g++ make eudev-dev libstdc++ libusb git python bash linux-headers
  - npm install -g truffle
  - npm install
  - truffle compile
  - cp src/config.js.dist src/config.js

stages:
  - lint
  - build_production
  - release_production

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  DOCKER_DRIVER: overlay2

run_js_linter:
  stage: lint
  script:
    - npm run lint

build_production:
  stage: build_production
  script:
    - echo $APP_CONFIG > src/config.js
    - NODE_ENV="production" npm run build

release_production:
  stage: release_production
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build . -f docks/Dockerfile
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}
